_src_path: /usr/local/anaconda3/lib/python3.8/site-packages
app: bloody-cli
artifactory_token_secret_name: ARTIFACTORY_RESOURCE_TOKEN
artifactory_url: https://artifactory.boschdevcloud.com/artifactory/api/pypi/lab000135-bios-bcai-pypi-local
artifactory_user_secret_name: ARTIFACTORY_RESOURCE_USER
author_email: mohamed.gad-elrab@de.bosch.com
author_fullname: Mohamed Gad-Elrab
copyright_license: All rights reserved
dev_line_length: 120
package_command_line_name: executable-ml-kgs
package_distribution_name: executable-ml-kgs
package_import_name: executable_ml_kgs
project_description: Library for excutable ML pipelines KGs.
project_homepage: ''
project_name: executable-ml-kgs
repository_name: executable-ml-kgs
repository_namespace: bcai-internal
