# Copyright (c) 2022 Robert Bosch GmbH and its subsidiaries. All rights reserved.

name: Remove Temporary Docs

on:
  pull_request:
    types: [closed]

jobs:
  remove-temporary-docs:
    name: Remove temporary docs
    runs-on: [self-hosted, Linux]
    container: ubuntu:latest

    steps:
      - name: Install prerequisites
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install --yes \
            curl \
            gcc \
            git \
            python3-dev \
            python3-venv

      - name: Set up poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --force
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure git
        run: |
          git config --add --global safe.directory "$GITHUB_WORKSPACE"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@bosch.com"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: poetry install

      - name: Determine version
        id: get_version
        run: |
          VERSION_JSON=$(poetry run mike list --rebase --json pr-${{github.event.number}})
          echo "::set-output name=json::$VERSION_JSON"

      - name: Remove temporary docs
        run: poetry run mike delete --rebase --push ${{ fromJson(steps.get_version.outputs.json).version }}
